// 获取UUID
GET {{host}}/uuid
Accept: application/json
Accept-Language: zh

###

// 获取图片验证码
GET {{host}}/captcha/image/9018af45-35c3-4f81-a2bb-b1517bd0653a
Accept: image/png

###

// 发送邮件验证码
POST {{host}}/captcha/email
Content-Type: application/json

{
  "email": "624508914@qq.com",
  "uuid": "9018af45-35c3-4f81-a2bb-b1517bd0653a",
  "code": "tsatEj"
}

###

// 发送手机验证码
POST {{host}}/captcha/phone
Content-Type: application/json

{
  "country_no": "86",
  "phone": "18179612275",
  "uuid": "9018af45-35c3-4f81-a2bb-b1517bd0653a",
  "code": "FMp2sd"
}

###