mode: debug # 运行模式，release / debug
port: 8080 # 运行端口
db: # Db 配置
  dsn: root:123456@tcp(127.0.0.1:3306)/yangyj?charset=utf8mb4&parseTime=True&loc=Local
redis: # Redis 配置
  default:
    host: 127.0.0.1
    port: 6379
    pwd:
    db: 1
    prefix: yangyj
  cache:
    host: 127.0.0.1
    port: 6379
    pwd:
    db: 1
    prefix: yangyj
cache: # 缓存配置
  type: redis
  prefix: cache
captcha: # 验证码配置
  expired: 10
  prefix: captcha
  skip_verify: false # 跳过验证
email: # 邮件配置，支持多个
  - host: smtp.exmail.qq.com
    port: 25
    username: xxx@xxx.com
    password: xxx
sms: # 短信配置
  kind: smsbao # 使用平台
  platform: # 短信平台配置
    smsbao: # 短信宝 https://smsbao.com
      username: xxx
      password: xxx
    aliyun: # 阿里云 https://aliyun.com
      appid: xxx
      appsecret: xxx
  template: # 短信模板配置
    captcha_code: # 验证码模板
      smsbao: # 短信宝模板，将你的短信内容直接写在这里即可
        zh: 【YANGYJ】您的验证码：%v，%v分钟内有效，请勿泄露给他人！
        en: 【YANGYJ】Your code is：%v, valid for %v minutes, do not disclose it to others！
      aliyun: # 阿里云模板，逗号分隔，签名在前，模板在后
        zh: YANGYJ,SMS_190095340
        en: YANGYJ,SMS_212471167